language: ruby
rvm:
  - 2.2.7
  - 2.3.4
  - 2.4.1
sudo: false
addons:
  code_climate:
    repo_token:
      secure: fyZ7Ycc23fzfh8bBiqPUhlJGcIcnanZWqVc4nsKDJeE1G5ScW01+ot1g4miDWxo7w80gKRKP/PfoYf6lOQ1B5yJJCV0Z5fjoTW3y+EKksMuGNCFaWh8R73MIPlVtfOazGyI2t3l4zDWoik906wHHNQJFveMZawvZGrVMWF6YxKg=
after_success:
  - bundle exec codeclimate-test-reporter
